# Generated by Django 5.0.1 on 2024-01-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_industry_state_job_job_type_job_industry_job_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
    ]
